name: "Sungrow Integration"
description: "Addon for integrating sungrow inverter without using Sungrow portal"
version: "1.3.0"
slug: "sungrow_integration"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386